Add support for new CIP 37 address
Conflux-Chain/js-conflux-sdk pull request #104
Opened 2021-01-23 15:03 UTC by Pana

For detail change check the CHANGELOG

2021-01-25 02:43 UTC, yqrashawn requested changes

2021-01-25 02:43 UTC, yqrashawn commented on README.md
> +The biggest difference you `must to know` is conflux object need chainId to figure out right CIP37 address. There are two way you can set it.
Shouldn't this be `netId` instead of `chainId` here?

2021-01-25 11:30 UTC, wangdayong228 requested changes
> Reviewed 2 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104)* status: 2 of 37 files reviewed, 18 unresolved discussions (waiting on @Pana)

___
*[CHANGE_LOG.md, line 5 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt74oQA-dBJdXXC-tN:-MRt74oQA-dBJdXXC-tO:b727lzs) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/CHANGE_LOG.md#L5)):*
> ```Markdown
> ## v1.5.0
> 
> * `Conflux`'s option can pass `chainId` now, and add a new method `updateChainId` to sync chainId from RPC.
> ```

currently could pass networkID
___
*[README.md, line 30 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7XL921hyohZFbHxV:-MRt7XL921hyohZFbHxW:bjlut7o) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/README.md#L30)):*
> ```Markdown
> ```
> 
> If you forgot to set chainId, you will see warning about it.
> ```

networkID
___
*[README.md, line 42 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7_y8BVCe3MTLzh7l:-MRt7_y8BVCe3MTLzh7m:bjlut7o) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/README.md#L42)):*
> ```Markdown
> const conflux = new Conflux({
>   url: 'http://test.confluxrpc.org',
>   chainId: 1,
> ```

networkID
___
*[README.md, line 73 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7b6A6rX-J0CuZ0Tu:-MRt7b6A6rX-J0CuZ0Tv:bjlut7o) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/README.md#L73)):*
> ```Markdown
>     url: 'http://test.confluxrpc.org',
>     logger: console,
>     chainId: 1,
> ```

networkID
___
*[docs/api.md, line 29 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7jnD5N8UvhWkfs7a:-MRt7jnD5N8UvhWkfs7b:bjlut7o) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L29)):*
> ```Markdown
>         - [InternalContract](#Conflux.js/Conflux/InternalContract)
>         - [close](#Conflux.js/Conflux/close)
>         - [updateChainId](#Conflux.js/Conflux/updateChainId)
> ```

networkID
___
*[docs/api.md, line 235 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7m_z-P4VJizc-N92:-MRt7m_z-P4VJizc-N93:bjlut7o) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L235)):*
> ```Markdown
> `number`
> 
> testnet chainId
> ```

networkID
___
*[docs/api.md, line 261 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7t763tfrziMxoSn2:-MRt7t763tfrziMxoSn3:bjlut7o) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L261)):*
> ```Markdown
> ```
> > const { Conflux } = require('js-conflux-sdk');
> > const conflux = new Conflux({url:'http://test.confluxrpc.org', chainId: 1});
> ```

networkID
___
*[docs/api.md, line 381 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7vbYAmr1XdmM21YH:-MRt7vbYAmr1XdmM21YI:bjlut7o) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L381)):*
> ```Markdown
> ### Conflux.prototype.updateChainId <a id="Conflux.js/Conflux/updateChainId"></a>
> 
> Update conflux chainId from RPC
> ```

networkID
___
*[docs/api.md, line 526 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt83oy0J7nPu5mQOBa:-MRt83oy0J7nPu5mQOBb:b-89jcx5) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L526)):*
> ```Markdown
>       nonce: 1449n,
>       stakingBalance: 0n,
>       admin: 'CFXTEST:TYPE.NULL:0000000000000000000000000000000000W5PHD2EJ',
> ```

charset is changed
___
*[docs/api.md, line 549 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt88Um6Jh2kQsWG4t7:-MRt88Un9_aVV8oF5g-e:b-89jcx5) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L549)):*
> ```Markdown
> 
> ```
> > await conflux.getBalance("cfxtest:00e1wwrgsdwpgnbv7p2u7wt78xwjf65vvsdz67gx0u");
> ```

charset is changed
___
*[docs/api.md, line 571 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt89zw25v4NjXQngsJ:-MRt89zw25v4NjXQngsK:b-89jcx5) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L571)):*
> ```Markdown
> 
> ```
> > await conflux.getStakingBalance('cfxtest:00e1wwrgsdwpgnbv7p2u7wt78xwjf65vvsdz67gx0u', 'latest_state');
> ```

charset is changed
___
*[docs/api.md, line 593 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt8BDY0FnPXJCMff62:-MRt8BDY0FnPXJCMff63:b-89jcx5) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L593)):*
> ```Markdown
> 
> ```
> > await conflux.getNextNonce("cfxtest:00e1wwrgsdwpgnbv7p2u7wt78xwjf65vvsdz67gx0u");
> ```

charset is changed
___
*[docs/api.md, line 616 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt8CBTA8KHBCEhcDz6:-MRt8CBTA8KHBCEhcDz7:b-89jcx5) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L616)):*
> ```Markdown
> ```
> > conflux.getAdmin('cfxtest:0272ybk8xduvr2sstaryjs3j8ba793wdk0s62tr4gj')
>    "CFXTEST:TYPE.USER:00E1WWRGSDWPGNBV7P2U7WT78XWJF65VVSDZ67GX0U"
> ```

charset is changed
___
*[docs/api.md, line 791 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt8DVm69hmWACQs9tt:-MRt8DVm69hmWACQs9tu:b-89jcx5) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L791)):*
> ```Markdown
>       deferredStateRoot: '0x50c0fcbc5bafa7d1dba7b19c87629830106a6be8d0adf505cdc656bb43535d69',
>       hash: '0xaf4136d04e9e2cc470703251ec46f5913ab7955d526feed43771705e89c77390',
>       miner: 'CFXTEST:TYPE.USER:00FK4FECP930DC31VEF3M4KRR3DTKWE1P8SKN4FE6W',
> ```

charset is changed
___
*[docs/api.md, line 878 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt8FBlDs2crB5Fl_sO:-MRt8FBlDs2crB5Fl_sP:b-89jcx5) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L878)):*
> ```Markdown
>       r: '0x495da01ae9f445847022a8bc7df0198577ba75f88b26699f61afb435bb9c50bc',
>       s: '0x2291051b1c53db1d6bfe2fb29be1bf512d063e726dc6b98aaf0f2259b7456be0',
>       to: 'CFXTEST:TYPE.USER:00FK4FECP930DC31VEF3M4KRR3DTKWE1P8SKN4FE6W'
> ```

charset is changed
___
*[docs/how_to_send_tx.md, line 15 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt8Vkr5M5953Lp_u7U:-MRt8Vks8xF9zC3ic9lp:bjlut7o) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/how_to_send_tx.md#L15)):*
> ```Markdown
>   const conflux = new Conflux({ 
>     url: 'http://test.confluxrpc.org',
>     chainId: 1,
> ```

networkID
___
*[src/Conflux.js, line 38 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt8m4l9mEN__8NDRa2:-MRt8m4l9mEN__8NDRa3:bjlut7o) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/src/Conflux.js#L38)):*
> ```JavaScript
>     defaultGasRatio = 1.1,
>     defaultStorageRatio = 1.1,
>     chainId,
> ```

networkID


<!-- Sent from Reviewable.io -->

2021-01-25 16:01 UTC, Pana reviewed
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104)* status: 0 of 37 files reviewed, 18 unresolved discussions (waiting on @wangdayong228 and @yqrashawn)

___
*[CHANGE_LOG.md, line 5 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt74oQA-dBJdXXC-tN:-MRuGQ8x7fAWZmtMZ6eK:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/CHANGE_LOG.md#L5)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

currently could pass networkID
</blockquote></details>

Done.
___
*[README.md, line 12 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRjlRKxKfRQQHdn8rxk-r1-12:-MRuGU2EB7NpKoHz32eV:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/README.md#L12)):*
<details><summary><i>Previously, yqrashawn (yqrashawn) wrote…</i></summary><blockquote>

Shouldn't this be `netId` instead of `chainId` here?
</blockquote></details>

Done.
___
*[README.md, line 30 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7XL921hyohZFbHxV:-MRuGW4Z1J0Xp0Bj58Wu:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/README.md#L30)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

networkID
</blockquote></details>

Done.
___
*[README.md, line 42 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7_y8BVCe3MTLzh7l:-MRuGWig-x6nJ-DZrjx9:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/README.md#L42)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

networkID
</blockquote></details>

Done.
___
*[README.md, line 73 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7b6A6rX-J0CuZ0Tu:-MRuGXmY-yj73tifSnGY:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/README.md#L73)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

networkID
</blockquote></details>

Done.
___
*[docs/api.md, line 29 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7jnD5N8UvhWkfs7a:-MRuGZ7RCNkZ5iZqjZdq:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L29)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

networkID
</blockquote></details>

Done.
___
*[docs/api.md, line 235 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7m_z-P4VJizc-N92:-MRuG_DC8PFsRXY6Sdmh:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L235)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

networkID
</blockquote></details>

Done.
___
*[docs/api.md, line 261 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7t763tfrziMxoSn2:-MRuGcPd96O7uOI6E3j0:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L261)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

networkID
</blockquote></details>

Done.
___
*[docs/api.md, line 381 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt7vbYAmr1XdmM21YH:-MRuGdAXEdaWjk0Dr1Bd:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L381)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

networkID
</blockquote></details>

Done.
___
*[docs/api.md, line 526 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt83oy0J7nPu5mQOBa:-MRuGewM63uB12uRqikx:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L526)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

charset is changed
</blockquote></details>

Done.
___
*[docs/api.md, line 549 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt88Um6Jh2kQsWG4t7:-MRuGfjc-1WtuROUYVzv:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L549)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

charset is changed
</blockquote></details>

Done.
___
*[docs/api.md, line 571 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt89zw25v4NjXQngsJ:-MRuGgAuAnqfaGhd9bk_:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L571)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

charset is changed
</blockquote></details>

Done.
___
*[docs/api.md, line 593 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt8BDY0FnPXJCMff62:-MRuGgeEEFJou6sF9R5f:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L593)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

charset is changed
</blockquote></details>

Done.
___
*[docs/api.md, line 616 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt8CBTA8KHBCEhcDz6:-MRuGhN-Br5ArDJ9yYgf:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L616)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

charset is changed
</blockquote></details>

Done.
___
*[docs/api.md, line 791 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt8DVm69hmWACQs9tt:-MRuGi-e0KZivu3OZl9C:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L791)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

charset is changed
</blockquote></details>

Done.
___
*[docs/api.md, line 878 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt8FBlDs2crB5Fl_sO:-MRuGiQf7fKTKmsx2qEL:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/api.md#L878)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

charset is changed
</blockquote></details>

Done.
___
*[docs/how_to_send_tx.md, line 15 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt8Vkr5M5953Lp_u7U:-MRuGqaYAV2QZNE0VGi2:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/docs/how_to_send_tx.md#L15)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

networkID
</blockquote></details>

Done.
___
*[src/Conflux.js, line 38 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRt8m4l9mEN__8NDRa2:-MRuGluBBe8k23FBSsOu:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/src/Conflux.js#L38)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

networkID
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-29 11:17 UTC, Pana reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-:-MSCrCs10UFgpuA1dCgj:bnfp4nl)* status: 0 of 39 files reviewed, 18 unresolved discussions (waiting on @wangdayong228 and @yqrashawn)



<!-- Sent from Reviewable.io -->

2021-01-30 04:28 UTC, wangdayong228 requested changes
> Reviewed 5 of 37 files at r1, 34 of 34 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104)* status: all files reviewed, 10 unresolved discussions (waiting on @Pana and @yqrashawn)

___
*[src/Conflux.js, line 185 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSDWUZo5NLLNcDgWe3W:-MSDWUZo5NLLNcDgWe3X:b-k3vnpe) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Conflux.js#L185)):*
> ```JavaScript
>   async updateNetworkId() {
>     const { networkId, chainId } = await this.getStatus();
>     this.networkId = networkId || chainId;
> ```

if networkId is zero and chindID is not , that will leads wrong.  I think only use networkId is ok
___
*[src/Message.js, line 118 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSDXHv45Z75gkbudVh5:-MSDXHv45Z75gkbudVh6:b-22d0vn) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Message.js#L118)):*
> ```JavaScript
>   sign(privateKey, networkId = CONST.MAINNET_ID) {
>     this.signature = Message.sign(privateKey, this.hash);
>     this.networkId = networkId;
> ```

I suggest to not set default value, if user sign in test net and without networkID, the result will be confused.
___
*[src/Transaction.js, line 68 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGQWMk8I2ZR7evp9L0:-MSGQWMk8I2ZR7evp9L1:b-xroipn) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Transaction.js#L68)):*
> ```JavaScript
>     const { r, s, v } = ecdsaSign(keccak256(this.encode(false)), privateKeyBuffer);
> 
>     this.from = format.address(addressBuffer, networkId || this.chainId);
> ```

remove chainID
___
*[src/util/format.js, line 310 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGTbr2AuX4FLz-a4eU:-MSGTbr39YJE8VbveSud:b7c2h7) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/util/format.js#L310)):*
> ```JavaScript
>  * Will convert an upper or lowercase address to a checksum address.
>  *
>  * @deprecated
> ```

Add replace suggestion?
___
*[src/util/format.js, line 489 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGUpmsB_QmKvrew8Ul:-MSGUpmsB_QmKvrew8Um:box6ups) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/util/format.js#L489)):*
> ```JavaScript
> }, { pick: true });
> 
> format.callTxAdvance = function (networkId, toHexAddress = false) {
> ```

Add comment because 'advance' is not very clear for understanding
___
*[src/util/sign.js, line 27 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGVOw11X2z3ADdEswF:-MSGVOw11X2z3ADdEswG:bxacqb6) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/util/sign.js#L27)):*
> ```JavaScript
>  * > Note: not support [RSKIP60](https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP60.md) yet
>  *
>  * @deprecated
> ```

suggest to add reason and replace suggestion
___
*[src/wallet/PrivateKeyAccount.js, line 42 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGVcppEFGuD2Tpxhgf:-MSGVcppEFGuD2Tpxhgg:b-tqvyjp) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/wallet/PrivateKeyAccount.js#L42)):*
> ```JavaScript
>     }
>    */
>   static random(entropy, networkId = CONST.MAINNET_ID) {
> ```

suggest not set networkID default to mainnet and leveal it to 0,  user must switch between mainnet and testnet frequently during develop and it will make confuse
___
*[src/wallet/PrivateKeyAccount.js, line 81 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGWKxT69FKOWOYpUnr:-MSGWKxT69FKOWOYpUns:b-tqvyjp) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/wallet/PrivateKeyAccount.js#L81)):*
> ```JavaScript
>   }
>    */
>   static decrypt(keystore, password, networkId = CONST.MAINNET_ID) {
> ```

suggest not set networkID default to mainnet and leveal it to 0,  user must switch between mainnet and testnet frequently during develop and it will make confuse
___
*[src/wallet/PrivateKeyAccount.js, line 101 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGWN2n1fQux7gV9rXN:-MSGWN2n1fQux7gV9rXO:b-tqvyjp) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/wallet/PrivateKeyAccount.js#L101)):*
> ```JavaScript
>   }
>    */
>   constructor(privateKey, networkId = CONST.MAINNET_ID) {
> ```

suggest not set networkID default to mainnet and leveal it to 0,  user must switch between mainnet and testnet frequently during develop and it will make confuse


<!-- Sent from Reviewable.io -->

2021-01-30 04:35 UTC, wangdayong228 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-:-MSGYFqC6t0a36wMiore:bnfp4nl)* status: all files reviewed, 12 unresolved discussions (waiting on @Pana and @yqrashawn)

___
*[src/Conflux.js, line 113 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGYa9b-43IKnrnuz7B:-MSGYa9b-43IKnrnuz7C:b192hr2) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Conflux.js#L113)):*
> ```JavaScript
>   _formatAddress(address) {
>     if (!this.networkId) {
>       console.warn('Conflux address: networkId is not set properly, please set it');
> ```

I think we can help user set networkId when networkId is zero, because we could get it from conflux.getStatus(), then it's ok when user create address without networkID
___
*[src/Conflux.js, line 183 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGZWhU82-F1m8n3H8c:-MSGZWhU82-F1m8n3H8d:b-7o0497) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Conflux.js#L183)):*
> ```JavaScript
>    * Update conflux networkId from RPC
>    */
>   async updateNetworkId() {
> ```

If we help user obtain networkID, this function will be unnecessary


<!-- Sent from Reviewable.io -->

2021-01-30 05:00 UTC, wangdayong228 requested changes
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104)* status: all files reviewed, 12 unresolved discussions (waiting on @Pana and @yqrashawn)

___
*[src/Conflux.js, line 38 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGbxYFBgMKgsd1GmvU:-MSGbxYFBgMKgsd1GmvV:b-kz0d8k) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Conflux.js#L38)):*
> ```JavaScript
>     defaultGasRatio = 1.1,
>     defaultStorageRatio = 1.1,
>     networkId,
> ```

If we do updateNetworkID in _formatAddress, param networkID here could be removed
___
*[src/Conflux.js, line 112 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGdbZd5WRmFX2Dd47M:-MSGdbZd5WRmFX2Dd47N:b-1rzbio) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Conflux.js#L112)):*
> ```JavaScript
> 
>   _formatAddress(address) {
>     if (!this.networkId) {
> ```

updateNetwork in here will help user set networkID and we can remove networkID param in constructor
___
*[src/Conflux.js, line 183 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGZWhU82-F1m8n3H8c:-MSGe5IA8KN7JXY7MQvN:b2m5m5e) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Conflux.js#L183)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

If we help user obtain networkID, this function will be unnecessary
</blockquote></details>

set this.networkID if this.networkID is 0


<!-- Sent from Reviewable.io -->

2021-01-30 11:56 UTC, Pana reviewed
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104)* status: 31 of 39 files reviewed, 12 unresolved discussions (waiting on @wangdayong228 and @yqrashawn)

___
*[src/Conflux.js, line 38 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGbxYFBgMKgsd1GmvU:-MSI72J2CjY3fL1-FWpI:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Conflux.js#L38)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

If we do updateNetworkID in _formatAddress, param networkID here could be removed
</blockquote></details>

Done.
___
*[src/Conflux.js, line 112 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGdbZd5WRmFX2Dd47M:-MSI75lbEWrzbMabbukF:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Conflux.js#L112)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

updateNetwork in here will help user set networkID and we can remove networkID param in constructor
</blockquote></details>

Done.
___
*[src/Conflux.js, line 113 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGYa9b-43IKnrnuz7B:-MSI6mTT5_pr0g-CPXkt:b-iulps0) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Conflux.js#L113)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

I think we can help user set networkId when networkId is zero, because we could get it from conflux.getStatus(), then it's ok when user create address without networkID
</blockquote></details>

wallet addPrivateKey method is also need the networkId, the _formatAddress can't cover all place
___
*[src/Conflux.js, line 185 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSDWUZo5NLLNcDgWe3W:-MSI12kg8xrvEgKEjQvf:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Conflux.js#L185)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

if networkId is zero and chindID is not , that will leads wrong.  I think only use networkId is ok
</blockquote></details>

Done.
___
*[src/Message.js, line 118 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSDXHv45Z75gkbudVh5:-MSI1ThY1V9aMilRB9Ip:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Message.js#L118)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

I suggest to not set default value, if user sign in test net and without networkID, the result will be confused.
</blockquote></details>

Done.
___
*[src/Transaction.js, line 68 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGQWMk8I2ZR7evp9L0:-MSI1RAI3OrePQKEwjIh:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/Transaction.js#L68)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

remove chainID
</blockquote></details>

Done.
___
*[src/util/format.js, line 310 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGTbr2AuX4FLz-a4eU:-MSI8WMp2PkuhpQvp4S2:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/util/format.js#L310)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

Add replace suggestion?
</blockquote></details>

Done.
___
*[src/util/format.js, line 489 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGUpmsB_QmKvrew8Ul:-MSI87jFDSKg4E1jdQJ_:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/util/format.js#L489)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

Add comment because 'advance' is not very clear for understanding
</blockquote></details>

Done.
___
*[src/util/sign.js, line 27 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGVOw11X2z3ADdEswF:-MSI8UQ96u-5L89JQPdn:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/util/sign.js#L27)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

suggest to add reason and replace suggestion
</blockquote></details>

Done.
___
*[src/wallet/PrivateKeyAccount.js, line 42 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGVcppEFGuD2Tpxhgf:-MSI7JCC6JGjOIp5e48l:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/wallet/PrivateKeyAccount.js#L42)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

suggest not set networkID default to mainnet and leveal it to 0,  user must switch between mainnet and testnet frequently during develop and it will make confuse
</blockquote></details>

Done.
___
*[src/wallet/PrivateKeyAccount.js, line 81 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGWKxT69FKOWOYpUnr:-MSI7IVV9lrkQXOm1QEu:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/wallet/PrivateKeyAccount.js#L81)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

suggest not set networkID default to mainnet and leveal it to 0,  user must switch between mainnet and testnet frequently during develop and it will make confuse
</blockquote></details>

Done.
___
*[src/wallet/PrivateKeyAccount.js, line 101 at r2](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MSGWN2n1fQux7gV9rXN:-MSI7He5B8Kv98R8_2zA:b-896fix) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/845d299fe57062fe42a4e8432cda8518e44b9d9c/src/wallet/PrivateKeyAccount.js#L101)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

suggest not set networkID default to mainnet and leveal it to 0,  user must switch between mainnet and testnet frequently during develop and it will make confuse
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-31 03:27 UTC, wangdayong228 approved these changes
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104)* status: all files reviewed, 1 unresolved discussion (waiting on @yqrashawn)



<!-- Sent from Reviewable.io -->

2021-01-31 09:05 UTC, Pana reviewed
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104)* status: all files reviewed, 1 unresolved discussion (waiting on @yqrashawn)

___
*[README.md, line 12 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRjlRKxKfRQQHdn8rxk-r1-12:-MSMgAe16X1hGRF-hKQW:bb6un1j) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/README.md#L12)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-01-31 09:06 UTC, Pana reviewed
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104)* status: all files reviewed, 1 unresolved discussion (waiting on @yqrashawn)

___
*[README.md, line 12 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104#-MRjlRKxKfRQQHdn8rxk-r1-12:-MSMgPQW-Mb93fYqU6vQ:bb6un1j) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/037bcc09d5a6157e8d69bcf07cc0fc5f9d10ada6/README.md#L12)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-01-31 13:06 UTC, yqrashawn approved these changes

2021-02-02 03:52 UTC, wangdayong228 approved these changes
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104)* status: all files reviewed, 1 unresolved discussion (waiting on @yqrashawn)



<!-- Sent from Reviewable.io -->

2021-02-02 03:57 UTC, yqrashawn approved these changes

2021-02-02 03:57 UTC, yqrashawn reviewed
> Reviewed 4 of 37 files at r1, 27 of 34 files at r2, 6 of 8 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104)* status: all files reviewed, 1 unresolved discussion (waiting on @yqrashawn)



<!-- Sent from Reviewable.io -->

2021-02-02 03:58 UTC, Pana reviewed
> Dismissed @yqrashawn from a discussion.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pana)



<!-- Sent from Reviewable.io -->

2021-02-02 03:59 UTC, merged